-- Create Database
CREATE DATABASE IF NOT EXISTS SPOTIFY_ANALYTICS;

-- Use Database
USE DATABASE SPOTIFY_ANALYTICS;

-- Create Schemas
CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS CURATED;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;
